version: '3'

services:
  web:
    container_name: web
    build:
      context: ./docker/web_context/
      dockerfile: ./Dockerfile
    user: node
    working_dir: /home/node/web
    volumes:
      - ./web:/home/node/web
    ports:
      - 3000:3000
    tty: true