version: '3'

services:
  web:
    container_name: web
    build:
      context: ./docker/web_context/
      dockerfile: ./Dockerfile
    user: node
    working_dir: /home/node/web
    volumes:
      - ./web:/home/node/web
    ports:
      - 3000:3000
    tty: true
  
  app:
    container_name: app
    build:
      context: ./docker/app_context/
      dockerfile: ./Dockerfile
    user: pyuser
    working_dir: /home/pyuser/app
    volumes:
      - ./app:/home/pyuser/app
    ports:
      - 8000:8000
    tty: true