version: '3'

services:
  web:
    container_name: web
    build:
      context: ./docker/web_context/
      dockerfile: ./Dockerfile
    user: node
    working_dir: /home/node/web
    volumes:
      - ./web:/home/node/web
    ports:
      - 3000:3000
    tty: true
  
  app:
    container_name: app
    build:
      context: ./docker/app_context/
      dockerfile: ./Dockerfile
    user: pyuser
    working_dir: /home/pyuser/app
    volumes:
      - ./app:/home/pyuser/app
    ports:
      - 8000:8000
    tty: true

  db:
    container_name: db
    build:
      context: ./docker/db_context/
      dockerfile: ./Dockerfile
    user: mysqluser
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_user
    volumes:
      - ./docker/db_context/init:/docker-entrypoint-initdb.d